name: .NET

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: | 
            6.0.x
            7.0.x
            8.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test Mediator.SourceGenerator
        run: dotnet test --no-restore --verbosity normal tests/Mediator.SourceGenerator.Tests/Mediator.SourceGenerator.Tests.csproj
      - name: Publish
        uses: GerardSmit/publish-nuget@v3.1.2
        with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: src/Directory.Build.props
          PROJECT_FILE_PATH: |
            src/Mediator/Mediator.csproj
            src/Mediator.DependencyInjection/Mediator.DependencyInjection.csproj
            src/Mediator.SourceGenerator/Mediator.SourceGenerator.csproj
